services:

  app:
    build: .
    depends_on:
      - mysql
      - prefect

    environment:
      PREFECT_API_URL: http://prefect:4200/api

    command: python -u flows/telecom_flow.py

  mysql:
    image: mysql:8

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telecom_db

    ports:
      - "3309:3306"

  prefect:
    image: prefecthq/prefect:3-latest

    command: prefect server start --host 0.0.0.0

    ports:
      - "4200:4200"
