services:

  weather-backend:
    build: ./backend
    container_name: weather-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped

  weather-frontend:
    build: ./frontend
    container_name: weather-frontend
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://weather-backend:5000
    depends_on:
      - weather-backend
    restart: unless-stopped

  prefect:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    restart: unless-stopped